### ISSUE TITLE
Unnecessary "and" rendered in css file

### ISSUE THREAD

**Issue by timmyomahony** [at-import/breakpoint#126] opened 2015-01-29 14:39 UTC
I'm using version `2.5.0` with `grunt-sass=0.17.0` (i.e. the C sass compiler) and I notice when I try the following breakpoint example: 

    $breakpoint: 1200px;
    body {
        background-color: blue;
        @include breakpoint($breakpoint) {
            background-color: green;
        }
    }

I get a warning in the CSS tab of the Firefox (35.0.1) console:

> Found reserved keyword 'and' when looking for media type.

Looking at the `.css` output, I'm seeing: 

    body {
        background-color: blue;
        @media  and (min-width: 1200px) {
            body {
                background-color: green;
            }
        }
    }

I'm not sure why there is an `and` in the output. I also tried: 

    @include breakpoint(0 1200px) {

and it rendered:

    @media  and (min-width: 0) and (max-width: 0) {

Any ideas why this is happening?

**Comment by Snugug** [comment] 2015-01-29 16:12
Duplicate of #121

**Closed by Snugug** 2015-01-29 16:12 UTC
